<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $ranking
 * @property enum $module
 * @property Doctrine_Collection $CategoryListings
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method integer             getRanking()          Returns the current record's "ranking" value
 * @method enum                getModule()           Returns the current record's "module" value
 * @method Doctrine_Collection getCategoryListings() Returns the current record's "CategoryListings" collection
 * @method Category            setName()             Sets the current record's "name" value
 * @method Category            setDescription()      Sets the current record's "description" value
 * @method Category            setRanking()          Sets the current record's "ranking" value
 * @method Category            setModule()           Sets the current record's "module" value
 * @method Category            setCategoryListings() Sets the current record's "CategoryListings" collection
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('ranking', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('module', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'marketplace',
              1 => 'events',
              2 => 'forum',
             ),
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Listing as CategoryListings', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}