<?php

/**
 * BaseCampus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $abbv
 * @property integer $city_id
 * @property City $City
 * @property Doctrine_Collection $CampusListings
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getAbbv()           Returns the current record's "abbv" value
 * @method integer             getCityId()         Returns the current record's "city_id" value
 * @method City                getCity()           Returns the current record's "City" value
 * @method Doctrine_Collection getCampusListings() Returns the current record's "CampusListings" collection
 * @method Campus              setName()           Sets the current record's "name" value
 * @method Campus              setAbbv()           Sets the current record's "abbv" value
 * @method Campus              setCityId()         Sets the current record's "city_id" value
 * @method Campus              setCity()           Sets the current record's "City" value
 * @method Campus              setCampusListings() Sets the current record's "CampusListings" collection
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campus');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('abbv', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('nameindex', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('User as CampusListings', array(
             'local' => 'id',
             'foreign' => 'campus_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}