<?php

/**
 * MailMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MailMessage extends BaseMailMessage
{
}
