<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
        const STATUS_NEW = 'new';
        const STATUS_LIVE = 'live';
        const STATUS_SUSPENDED = 'suspended';

        /**
         * Sets the password fo this user
         * @param <type> $v
         */
	public function setPassword($v) {

		

		
			$salt = $this->genSalt();
			$this->setSalt ( $salt );
			$this->setPasswordHash ( sha1 ( $salt . $v ) );
			
		

	}

        /**
         * Generate a 32 length hash for multiple purpos
         * @return <type>
         */
        public function genSalt(){
            return   md5 ( rand ( 100000, 999999 ) . $this->getEmail() );
        }


        /**
         * Sends an email with registration instruction
         */
        public function sendRegisterEmail(sfActions $action){

            $msg= $action->getPartial('partials/emailRegister', array('hash'=>$this->getRegisterHash()));            
            $mailer = $action->getMailer();
            
            $res = $mailer->composeAndSend("registration-noreply@".sfConfig::get('app_site_domain'), $this->getEmail(), sfConfig::get('app_site_name')." Account Registration", $msg);

            return $res;
            
        }

        /**
         * Sends an email for password reset
         * @return <type>
         */
        public function sendPassResetEmail(sfActions $action){
                         
            $mailer = $action->getMailer();
            $msg= $action->getPartial('partials/emailPassReset', array('email'=>$this->getEmail(), 'hash'=>$this->getResetPasswordHash()));

            $res = $mailer->composeAndSend("account-recovery-noreply@".sfConfig::get('app_site_domain'), $this->getEmail(), sfConfig::get('app_site_name')." Password Assistance", $msg);
            return $res;
            
        }
        /**
         * Sends an email for password reset
         * @return <type>
         */
        public function sendPassResetNotificationEmail(sfActions $action){

            $mailer = $action->getMailer();
            $msg= $action->getPartial('partials/emailPassResetNotification', array('name'=>$this->getNickName()));

            $res = $mailer->composeAndSend("account-recovery-noreply@".sfConfig::get('app_site_domain'), $this->getEmail(), sfConfig::get('app_site_name')." Password Change", $msg);
            return $res;

        }

        /**
         * Sends an email for account activation
         * @return <type>
         */
        public function sendActivatedEmail(sfActions $action){

            $mailer = $action->getMailer();
            $msg= $action->getPartial('partials/emailActivated', array('nickname'=>$this->getNickName()));

            $res = $mailer->composeAndSend("account-activated-noreply@".sfConfig::get('app_site_domain'), $this->getEmail(), sfConfig::get('app_site_name')." Account Activated", $msg);
            return $res;

        }


}
