<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/05 09:11:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=campuscenter',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
