<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/09/06 11:05:55
sfConfig::add(array(
  'app_category_listings_per_page' => 20,
  'app_enable_remember_me' => 'on',
  'app_site_domain' => 'campuscenter.com.au',
  'app_site_name' => 'CampusCenter',
  'app_site_root' => '/cc/web',
));
