<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Image extends BaseImage
{

    /**
     * Return HTML tag string
     *
     * @return string HTML image tag
     */
    public function toHTMLTag($isThumb=false){
        return '<img class="'.($isThumb?'listingThumb':'').'" title="'.htmlentities($this->getDescription()).'" src="'.$this->getUrl().'" />';
    }


}
