<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/06 11:05:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=campuscenter',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
