<?php
// auto-generated by sfViewConfigHandler
// date: 2010/09/12 22:55:53
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'signInFormFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'signInFeedbackFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'passResetFormFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'passResetFeedbackFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'registerFormFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'registerFeedbackFancySuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'passResetNewPassFormSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'activateFormSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'signInFormFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'signInFeedbackFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'passResetFormFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'passResetFeedbackFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'registerFormFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'registerFeedbackFancySuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'fancyLayout' ? false : 'fancyLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('popup.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
  $response->addJavascript('jquery.blockUI.js', '', array ());
}
else if ($templateName.$this->viewName == 'passResetNewPassFormSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'simpleLayout' ? false : 'simpleLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addStylesheet('jquery.fancybox.css', '', array ());
}
else if ($templateName.$this->viewName == 'activateFormSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'simpleLayout' ? false : 'simpleLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addStylesheet('jquery.fancybox.css', '', array ());
  $response->addStylesheet('autocomplete.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('autocomplete/jquery.autocomplete.min.js', '', array ());
  $response->addJavascript('validate/jquery.validate.min.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('custom.css', '', array ());
  $response->addStylesheet('jquery.fancybox.css', '', array ());
  $response->addJavascript('jquery', '', array ());
  $response->addJavascript('base.js', '', array ());
  $response->addJavascript('jquery.fancybox.js', '', array ());
}

