<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $listing_id
 * @property string $text
 * @property integer $weight
 * @property Listing $Listing
 * 
 * @method integer getListingId()  Returns the current record's "listing_id" value
 * @method string  getText()       Returns the current record's "text" value
 * @method integer getWeight()     Returns the current record's "weight" value
 * @method Listing getListing()    Returns the current record's "Listing" value
 * @method Tag     setListingId()  Sets the current record's "listing_id" value
 * @method Tag     setText()       Sets the current record's "text" value
 * @method Tag     setWeight()     Sets the current record's "weight" value
 * @method Tag     setListing()    Sets the current record's "Listing" value
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('listing_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Listing', array(
             'local' => 'listing_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}