<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $CityListings
 * @property Doctrine_Collection $CityCampuses
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getCityListings() Returns the current record's "CityListings" collection
 * @method Doctrine_Collection getCityCampuses() Returns the current record's "CityCampuses" collection
 * @method City                setName()         Sets the current record's "name" value
 * @method City                setCityListings() Sets the current record's "CityListings" collection
 * @method City                setCityCampuses() Sets the current record's "CityCampuses" collection
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('city');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User as CityListings', array(
             'local' => 'id',
             'foreign' => 'city_id'));

        $this->hasMany('Campus as CityCampuses', array(
             'local' => 'id',
             'foreign' => 'city_id'));
    }
}