<?php

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $listing_id
 * @property integer $user_id
 * @property string $name
 * @property string $description
 * @property string $url
 * @property enum $audit_status
 * @property Listing $Listing
 * @property User $User
 * 
 * @method integer getListingId()    Returns the current record's "listing_id" value
 * @method integer getUserId()       Returns the current record's "user_id" value
 * @method string  getName()         Returns the current record's "name" value
 * @method string  getDescription()  Returns the current record's "description" value
 * @method string  getUrl()          Returns the current record's "url" value
 * @method enum    getAuditStatus()  Returns the current record's "audit_status" value
 * @method Listing getListing()      Returns the current record's "Listing" value
 * @method User    getUser()         Returns the current record's "User" value
 * @method Image   setListingId()    Sets the current record's "listing_id" value
 * @method Image   setUserId()       Sets the current record's "user_id" value
 * @method Image   setName()         Sets the current record's "name" value
 * @method Image   setDescription()  Sets the current record's "description" value
 * @method Image   setUrl()          Sets the current record's "url" value
 * @method Image   setAuditStatus()  Sets the current record's "audit_status" value
 * @method Image   setListing()      Sets the current record's "Listing" value
 * @method Image   setUser()         Sets the current record's "User" value
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('listing_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 1024,
             ));
        $this->hasColumn('audit_status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'live',
              2 => 'canceled',
             ),
             'default' => 'new',
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Listing', array(
             'local' => 'listing_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}