<?php

/**
 * BaseMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $nick_name
 * @property string $email
 * @property enum $status
 * @property Doctrine_Collection $MemberListings
 * @property Doctrine_Collection $MemberComments
 * @property Doctrine_Collection $MemberImages
 * 
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method string              getNickName()       Returns the current record's "nick_name" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method enum                getStatus()         Returns the current record's "status" value
 * @method Doctrine_Collection getMemberListings() Returns the current record's "MemberListings" collection
 * @method Doctrine_Collection getMemberComments() Returns the current record's "MemberComments" collection
 * @method Doctrine_Collection getMemberImages()   Returns the current record's "MemberImages" collection
 * @method Member              setUserId()         Sets the current record's "user_id" value
 * @method Member              setNickName()       Sets the current record's "nick_name" value
 * @method Member              setEmail()          Sets the current record's "email" value
 * @method Member              setStatus()         Sets the current record's "status" value
 * @method Member              setMemberListings() Sets the current record's "MemberListings" collection
 * @method Member              setMemberComments() Sets the current record's "MemberComments" collection
 * @method Member              setMemberImages()   Sets the current record's "MemberImages" collection
 * 
 * @package    campuscenter
 * @subpackage model
 * @author     David Lin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nick_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'new',
              1 => 'live',
              2 => 'suspended',
             ),
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Listing as MemberListings', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Comment as MemberComments', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Image as MemberImages', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}